v0.0.1
logzio/ezkonnect-server pull request #1
Opened 2023-03-16 14:54 UTC by yotamloe

First release of the `EZkonnect-server` :
- API endpoints: `[GET] /api/v1/state`, `[POST] /api/v1/annotate/traces`, `[POST] /api/v1/annotate/logs`.
- Docker file and Kubernetes manifests.

The `dev` [branch](https://github.com/logzio/ezkonnect-server/tree/dev) contains a working version, we can start work with it and make changes as we go.

2023-06-04 14:23 UTC, mirii1994 commented on Makefile
> +DOCKER_REPO := yotamloe/$(IMAGE_NAME):$(IMAGE_TAG)
Your repo :)

2023-06-04 15:08 UTC, mirii1994 requested changes
Great work!
Please see my comments :)

2023-06-04 15:08 UTC, mirii1994 commented on api/annotate/traces.go
> +	isValidAction := req.Action == "add" || req.Action == "delete"
I'd prefer if:
1. we'll move these to be consts (maybe even under common.go)
2. In the function create an array of supported kinds and supported actions.
3. Iterate through those arrays to check validity
4. Use those consts throughout the code

2023-06-04 15:08 UTC, mirii1994 commented on api/annotate/traces.go
> +		var annotationKey = "logz.io/traces_instrument"
Please move it to be a const and use it throughout the code

2023-06-04 15:08 UTC, mirii1994 commented on api/annotate/traces.go
> +		http.Error(w, "Error getting Kubernetes config", http.StatusInternalServerError)
For maintenance purposes - would it be better if we'd have the message in a variable, and refer to it in both logger & http error?

2023-06-04 15:08 UTC, mirii1994 commented on api/annotate/traces.go
> +// kind: kind of the resource (deployment or statefulset)
Refer to where the consts are for supported kinds

2023-06-04 15:08 UTC, mirii1994 commented on api/annotate/traces.go
> +// action: action to perform (add or delete)
Refer to where the consts are for supported actions

2023-06-05 12:13 UTC, yotamloe commented on Makefile
> +IMAGE_TAG := 0.0.1
Sure I know these workflows, just didn't got to that yet :)

2023-06-05 14:08 UTC, mirii1994 approved these changes
YAAAAS.

2023-06-05 14:44 UTC, merged